import Button from "./Button"
import ResumeCard from "./ResumeCard"
import Heading from "./Heading"
import FollowMe from "./FollowMe"
import Skill from "./Skill"
import ServiceCard from "./ServiceCard"
import Exptab from "./Exptab"
import ProjectCard from "./ProjectCard"
import Testimonial from "./Testimonial"
import BlogCard from "./BlogCard"
export {Button,ResumeCard,Heading,FollowMe,Skill,ServiceCard,Exptab,ProjectCard,Testimonial,BlogCard}